# Generated by Django 4.0.6 on 2022-07-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='fist_name',
        ),
    ]
