# Generated by Django 4.0.6 on 2022-07-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='oraganisation',
            new_name='organisation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
