# Generated by Django 4.0.6 on 2022-07-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_full_name_client_fist_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
