# Generated by Django 4.0.6 on 2022-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_oraganisation_client_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domain',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
