# Generated by Django 4.0.6 on 2022-07-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_country_alter_client_password_and_more'),
        ('client', '0003_alter_client_domain'),
    ]

    operations = [
    ]
